cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('shop1/', include('shop1.urls', namespace='shop1')),
    path('shop2/', include('shop2.urls', namespace='shop2')),
    path('shop3/', include('shop3.urls', namespace='shop3')),
    path('shop4/', include('shop4.urls', namespace='shop4')),
    path('accounts/',include('accounts.urls', namespace='accounts'))
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop2/urls.py
from django.urls import path
from . import views

app_name = 'shop2'

urlpatterns = [

# Baking course view
    path('', views.product_list, name='product_list'),
    path('available-sessions/', views.available_course_sessions, name='available_course_sessions'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]




"""

    path('', views.product_list, name='product_list'),
    path('Products', views.product_list, name='product_list'),

    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

    path('instructors', views.instructors, name='instructors'),
    path('registration', views.registration, name='registration'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart')
"""

shop2/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from shop.models import Product
from shop3.models import Studio
from django.utils import timezone

def validate_time(value):
    # Define allowed times
    allowed_times = [(9, 0), (10, 0), (11, 0), (12, 0), (13, 0), (14, 0), (15, 0), (16, 0), (17, 0)]  # (hour, minute) tuples
    
    # Check if the time is in allowed times
    if (value.hour, value.minute) not in allowed_times:
        raise ValidationError(f"Start time must be one of the following: {allowed_times}.")


class MenuItem(models.Model):
    id = models.AutoField(primary_key=True) # #key
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, db_index=True,default="")
    description = models.TextField()
    image = models.ImageField(upload_to='menuitem',
                              blank=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.name  


class Instructor(models.Model):
    id = models.AutoField(primary_key=True) # key
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, db_index=True, default="")
    description = models.TextField()
    image = models.ImageField(upload_to='instructor',
                              blank=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.name  


class CourseSession(models.Model): 
    id = models.AutoField(primary_key=True) # key
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, db_index=True, default="")
    product_id = models.ForeignKey(Product,
                                 related_name='products',
                                 on_delete=models.PROTECT)
    contents = models.TextField()
    menu_name= models.ForeignKey(MenuItem,
                                 related_name='menuitems',
                                 on_delete=models.PROTECT)
    instructor = models.ForeignKey(Instructor, 
                                    related_name='instructors',
                                    on_delete=models.PROTECT)
    start_date_time = models.DateTimeField(validators=[validate_time])
    end_date_time = models.DateTimeField(validators=[validate_time])
    studio_name = models.ForeignKey(Studio,
                                 related_name='studios',
                                 on_delete=models.PROTECT)
    location = models.CharField(max_length=100)
    quota = models.IntegerField(default=0)
    filled_place = models.IntegerField(default=0)
    available = models.BooleanField(default=True)
    last_modified = models.DateTimeField(auto_now=True)
    modified_by = models.CharField(max_length=100)


    def __str__(self):
        return self.name  
    
    def get_absolute_shop2_url(self):
        return reverse('shop2:product_detail',
                       args=[self.id, self.slug])

shop2/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import F  
from cart.forms import CartAddProductForm
from shop.models import Category, Product
from .models import Instructor
from django.shortcuts import render
from django.http import JsonResponse
from .models import MenuItem, Instructor, CourseSession
from django.db.models import F, ExpressionWrapper, IntegerField

def product_list(request):
    # Fetch all available MenuItem records
    menu_items = MenuItem.objects.filter(available=True)
    
    # Fetch all available Instructor records
    instructors = Instructor.objects.filter(available=True)

    # Render the template with the menu items and instructors
    return render(request, 'shop2/list.html', {
        'menu_items': menu_items,
        'instructors': instructors,
    })
def available_course_sessions(request):
    # Fetch course sessions where quota is greater than or equal to filled places
    course_sessions = CourseSession.objects.filter(available=True, quota__gte=F('filled_place')).annotate(
        available_places=ExpressionWrapper(
            F('quota') - F('filled_place'),
            output_field=IntegerField()
        )
    )
    return render(request, 'shop2/registration.html', {
        'course_sessions': course_sessions,
    })

def product_detail(request, id, slug):
    courses_sessions = get_object_or_404(CourseSession,
                                id=id,
                                slug=slug,
                                available=True)
    print('courses_sessions : ', courses_sessions)
    print('courses_sessions.product_id : ', courses_sessions.product_id)
    product = get_object_or_404(Product,
                                name=courses_sessions.product_id,)
    print('product : ', product)
    

    # Construct product description with line breaks
    formatted_start_date_time = courses_sessions.start_date_time.strftime('%d-%b-%y %H:%M')

    # Construct product description with line breaks
    product_desc = (
        f"{courses_sessions.name}\n"
        f"{courses_sessions.instructor.name}\n"
        f"{courses_sessions.location}\n"
        f"{formatted_start_date_time}"
    )
    
    cart_product_form = CartAddProductForm(initial={
        'product_desc': product_desc,            # Pass product des description
    })
    return render(request,
                  'shop2/detail.html',
                  {'product': product, 
                   'cart_product_form': cart_product_form})

templates/shop2/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}

<style>
  .background {
      background-image: url("{% static 'img/common-img/backg02.jpg' %}");
      background-size: cover;
      background-position: center;
      background-repeat: no-repeat;
      height: 200vh;
      position: relative;
  }

  
  textarea {
      width: 100%;  /* Make the textarea responsive */
      resize: vertical;  /* Allow vertical resizing */
    }
  
</style>

<div class='background'>
  <div class="container mt-0">
    <div class="card">
      <div class="row no-gutters">
        <div class="col-md-6">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}
          {% static 'img/no_image.png' %}{% endif %}" alt="{{ product.name }}" class="card-img" style="object-fit: cover; height: 100%; width: 100%;">
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <h3 class="card-title">{{ product.name }}</h3>
            
            <p class="price h5">${{ product.price }} /place</p>

            <form action="{% url 'cart:cart_add' product.id %}" method="post" class="mt-3">
              {% csrf_token %}
              <div class textarea>
              <div class="form-group">
                {{ cart_product_form.product_desc }}  <!-- Product description -->
                <br>
              </div>
            </div>
              <div class="form-group">
                <label for="quantity">Number of place(s):</label>
                {{ cart_product_form.quantity }}  <!-- Quantity selection -->
              </div>

              <button type="submit" class="btn btn-primary">Add to cart</button>  <!-- Button styling -->
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  
{% endblock %}

templates/shop2/list.html
{% extends 'base.html' %}
{% block title %}Baking Course{% endblock %}
{% load static %}
{% block content %}

    <style>
        .background {
            background-image: url("{% static 'img/common-img/backg02.jpg' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 200vh;
            position: relative;
        }

        .booking-button {
            position: fixed;
            right: 20px;
            bottom: 20px;
            background-color: #ff6347; /* Changing to a brighter color */
            color: white;
            padding: 20px 40px; /* Further increased padding for a larger button */
            border-radius: 10px; /* Rounded corners for a modern look */
            cursor: pointer;
            transition: background-color 0.3s;
            font-size: 20px; /* Larger font size for better visibility */
            text-transform: uppercase; /* Uppercase text for emphasis */
            font-weight: bold; /* Bold text for emphasis */
            etter-spacing: 2px; /* Increased letter spacing for clarity */
        }
        .booking-button:hover {
            background-color: #ff4837; /* Darker color on hover for contrast */

        body {
            font-family: 'Arial', sans-serif;
            background-color: #f5e6ca;
        }

        h1 {
            color: #800080;
            margin-bottom: 20px;
        }

        /* Media Queries for responsiveness */
        @media (max-width: 600px) {
            h1, h2 {
                font-size: 1.5em; /* Smaller headings on mobile */
            }
        }

        .card-body {
            padding: 0.5rem;  /* Adjust this value as needed */
        }
        .card-body p {
            margin: 0;  /* Ensures no margin around the paragraph */
        }
    </style>

    <div class='background'>
        <div class="container mt-0">
            <h2 class="mt-0 text-center">Choose Your Favourite Taste</h2>
            <div class="row">
                {% for menu_item in menu_items %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            <div class="card-body text-center">
                                <label for="course{{ forloop.counter }}">
                                    <strong>{{ menu_item.name }}</strong>
                                </label>
                                {% if menu_item.image %}
                                    <img src="{{ menu_item.image.url }}" alt="{{ menu_item.name }}" class="img-fluid mt-2">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="card mt-0 mb-0">
                <div class="card-body p-1">  <!-- Reduced padding -->
                    <p class="m-0"> <!-- Remove margin from the paragraph -->
                        Come learn the art of baking from our renowned Chef. With years of experience and a passion for pastries, they will guide you through the secrets of creating delectable desserts that will delight your taste buds and impress your friends and family.
                    </p>
                </div>
            </div>

            <div class="card mt-0">
                <div class="card-body">
                    <div class="row">
                        {% for instructor in instructors %}
                            <div class="col-md-4 mb-0">
                                <div class="card text-center">
                                    <div class="card-body">
                                        <h5>{{ instructor.name }}</h5>
                                        {% if instructor.image %}
                                            <img src="{{ instructor.image.url }}" alt="{{ instructor.name }}" class="img-fluid">
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <p>No instructors available at the moment.</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </div>


<a href="{% url 'shop2:available_course_sessions' %}" class="booking-button">Book Now</a>
{% endblock %}

templates/shop2/registration.html
{% extends "base.html" %}
{% load static %}
{% block title %}Available Course Sessions{% endblock %}
{% block content %}
<div class="background">
    <div class="container mt-0">
        <h4 class="text-center">Available Course Sessions</h4>
        <div class="row">
            {% for session in course_sessions %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ session.name }}</h5>
                            <p class="card-text">{{ session.contents }}</p>
                            <p class="card-text">
                                <strong>Instructor:</strong> {{ session.instructor.name }}<br>
                                <strong>Location:</strong> {{ session.location }}<br>
                                <strong>Start:</strong> {{ session.start_date_time }}<br>
                                <strong>Class size:</strong> {{ session.quota }} <br> 
                                <strong>Available place(s):</strong> {{ session.filled_place }} <!-- Calculate available places -->
                            </p>
                            <a href="{{ session.get_absolute_shop2_url }}" class="btn btn-primary">Select Session</a>
                        </div>
                    </div>
                </div>
            {% empty %}
                <p>No available course sessions at the moment.</p>
            {% endfor %}
        </div>
    </div>
</div>
{% block extra_css %}
<style>
    .background {
        background-image: url("{% static 'img/shop4-detail-background.jpg' %}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        height: 200vh;
        position: relative;
    }

    .card-img-top {
        width: 100%;
        height: 200px;
        object-fit: cover;
    }
</style>
{% endblock %}
{% endblock %}