cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('shop1/', include('shop1.urls', namespace='shop1')),
    path('shop2/', include('shop2.urls', namespace='shop2')),
    path('shop3/', include('shop3.urls', namespace='shop3')),
    path('shop4/', include('shop4.urls', namespace='shop4')),
    path('accounts/',include('accounts.urls', namespace='accounts'))
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop1/urls.py
from django.urls import path
from . import views


app_name = 'shop1'


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('Products', views.product_list, name='product_list'),
    path('ordering/<int:id>/<slug:slug>', views.ordering, name='ordering'),
    path('ordering', views.ordering, name='ordering'),
    path('<int:id>', views.category_list, name='category_list'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop1/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from shop.models import Category, Product #ForeignKey
from django.utils import timezone

class ProductDetail(models.Model): # Table Name: ProductDetail
    CAKE_SIZES = [
        ('12cm', '12cm'),
        ('18cm', '18cm'),
        ('22cm', '22cm'),
        ('28cm', '28cm'),
    ]

    CAKE_WEIGHT = [
        ('400g', '400g'),
        ('850g', '850g'),
        ('1.2kg', '1.2kg'),
        ('1.8kg', '1.8kg'),
    ]

    CAKE_DESC = [
        ('For 3 - 4 persons', 'For 3 - 4 persons'),
        ('For 8 - 10 persons', 'For 8 - 10 persons'),
        ('For 10 - 12 persons', 'For 10 - 12 persons'),
        ('For 18 - 20 persons', 'For 18 - 20 persons'),
    ]

    id = models.AutoField(primary_key=True) # key

    allergen = models.TextField(blank=True) # text field / blank = true

    First_size = models.CharField(max_length=50, default="12cm", choices=CAKE_SIZES) # choices="12cm" 
    First_weight = models.CharField(max_length=50, default="400g", choices=CAKE_WEIGHT) # choices="400g"
    First_desc = models.CharField(max_length=50, default="For 3 - 4 persons", choices=CAKE_DESC) # choices="For 3 - 4 persons"
    First_price = models.IntegerField()

    Second_size = models.CharField(max_length=50, default="18cm", choices=CAKE_SIZES) # choices="18cm" 
    Second_weight = models.CharField(max_length=50, default="850g", choices=CAKE_WEIGHT) # choices="850g"
    Second_desc = models.CharField(max_length=50, default="For 8 - 10 persons", choices=CAKE_DESC) # choices="For 8 - 10 persons"
    Second_price = models.IntegerField()

    Third_size = models.CharField(max_length=50, default="22cm", choices=CAKE_SIZES) # choices="22cm" 
    Third_weight = models.CharField(max_length=50, default="1.2kg", choices=CAKE_WEIGHT) # choices="1.2kg"
    Third_desc = models.CharField(max_length=50, default="For 10 - 12 persons", choices=CAKE_DESC) # choices="For 10 - 12 persons"
    Third_price = models.IntegerField()

    Fourth_size = models.CharField(max_length=50, default="28cm", choices=CAKE_SIZES) # choices="22cm" 
    Fourth_weight = models.CharField(max_length=50, default="1.8kg", choices=CAKE_WEIGHT) # choices="1.8kg"
    Fourth_desc = models.CharField(max_length=50, default="For 18 - 20 persons", choices=CAKE_DESC) # choices="For 18 - 20 persons"
    Fourth_price = models.IntegerField()

    product = models.ForeignKey(Product,
                                 related_name='product_detail',
                                 on_delete=models.PROTECT)
    
    name = models.CharField(max_length=50, default="no name", blank=True, null=True)  
    
    def __str__(self):
        return self.name

class Cakes(models.Model):
    CAKE_SIZES = [
        ('12cm', '12cm'),
        ('18cm', '18cm'),
        ('22cm', '22cm'),
        ('28cm', '28cm'),
    ]

    CAKE_WEIGHT = [
        ('400g', '400g'),
        ('850g', '850g'),
        ('1.2kg', '1.2kg'),
        ('1.8kg', '1.8kg'),
    ]

    CAKE_DESC = [
        ('For 3 - 4 persons', 'For 3 - 4 persons'),
        ('For 8 - 10 persons', 'For 8 - 10 persons'),
        ('For 10 - 12 persons', 'For 10 - 12 persons'),
        ('For 18 - 20 persons', 'For 18 - 20 persons'),
    ]
    
    id = models.AutoField(primary_key=True) # key
    Cake_Sizes = models.CharField(max_length=50, choices=CAKE_SIZES)
    Cake_Weight = models.CharField(max_length=50, choices=CAKE_WEIGHT)
    Cake_Desc = models.CharField(max_length=50, choices=CAKE_DESC)

#    def __str__(self):
#        return self.name 

shop1/forms.py
from django import forms
from .models import Ordering

shop1/views.py
import calendar
from django.shortcuts import render, get_object_or_404, redirect
from cart.forms import CartAddProductForm
from shop.models import Category, Product
from shop1.models import ProductDetail
from django.core.paginator import EmptyPage,PageNotAnInteger, Paginator
from datetime import datetime, timedelta
from django.utils import timezone
from cart.cart import Cart
from cart.forms import CartAddProductForm
from decimal import Decimal
from django.conf import settings
from django.contrib.sessions.models import Session
import json
from decimal import Decimal
import uuid

def product_list(request, slug=None):

    category = None
    categories = Category.objects.filter(shop_id=1).order_by('id')
    products = Product.objects.filter(available=True, shop_id=1).order_by('name')
    
    print("[product_list] No. of categories:" , len(categories))
    print("[product_list] No. of products:" , len(products))
    
    #paginator = Paginator(products, 3)
    #page = request.GET.get('page')
    #paged_products = paginator.get_page(page)

    print("category slug:", slug)

    if slug:
        category = get_object_or_404(Category, slug=slug)
        products = Product.filter(category=category)

    context={'category': category,
                   'categories': categories,
                   'products': products}

    print('Before exiting product_list')


    return render(request,
                  'shop1/list.html',
                  context)


def category_list(request, id, category_slug=None):

    category = None
    #! Display all categories

    # categories = Category.objects.filter(shop_id=1)

    CategoryName = Category.objects.get(id=id)
    
    print("[category_detail] Categories Name:" , CategoryName)

    #! Display all available products
    products = Product.objects.filter(available=True, category_id=id)
    
    #paginator = Paginator(products, 3)
    #page = request.GET.get('page')
    #paged_products = paginator.get_page(page)
    # @ pass database records into listings context
    #context = {'products': paged_products}
    
    print("[category_detail] Categories Name:" , CategoryName)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {
                'category': category,
                'products': products,
                'category_name': CategoryName
    }    
    return render(request,
                  'shop1/category.html',
                   context)


def product_detail(request, id, slug):
    
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    category_name = product.category.name  # Access the category name directly
    product_detail_items = ProductDetail.objects.filter(product=product)
    num_items = len(product_detail_items)

    if product_detail_items.exists():
        print("product.name ", product.name)
        print("Number of items in product_detail_items:", num_items)
        print("Categories Name:" , category_name)
    
    d_delivery_date_list = {}
    x = range(2, 14)
    for n in x:
        p_day_01 = datetime.now()
        p_day_n = p_day_01 + timedelta(n)
        d_delivery_date_list[n] = p_day_n.strftime('%Y-%m-%d') + " , " + p_day_n.strftime('%A')
        
        print("Day", n, p_day_n.strftime('%Y-%m-%d'))
        print("Day", p_day_n.strftime('%A'))   

    present_day = datetime.now()
    earliest_date = present_day + timedelta(2)

    print("present_day", present_day.strftime ('%Y-%m-%d'))    
    print("delivery_date.items", d_delivery_date_list)

    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop1/detail.html',
                  {'product': product,
                   'category': category_name,
                   'cart_product_form': cart_product_form,
                   'product_detail_items': product_detail_items,
                   'present_day': present_day,
                   'earliest': earliest_date,
                   'delivery_date': d_delivery_date_list})
    

def ordering(request, id, slug):

    
    if request.method == 'POST':
        
        print('In ordering')

        product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
        
        contact_person = request.POST.get('contact_person', '').strip()
        print('contact person : ', contact_person)
  

        contact_number = request.POST.get('contact_number', '').strip()
        print('contact number : ', contact_number)
        

        contact_email = request.POST.get('contact_email', '').strip()
        print('contact email :', contact_email)

        qty = request.POST.get('qty', '1').strip()  # Get qty from POST data
        print("qty : ", qty)

        if 'cake_size_weight_price' in request.POST:
            cake_size_weight_price = request.POST.get('cake_size_weight_price')
            parts = request.POST.get('cake_size_weight_price').split("/")
            cake_size = parts[0].strip()
            cake_weight = parts[1].strip()
            cake_desc = parts[2].strip()
            cake_price = int(parts[3])
            print("cake_size_weight_price :", cake_size, cake_weight, cake_desc, cake_price)

        if 'pickup_delivery' in request.POST:
            parts = request.POST.get('pickup_delivery').split("/")
            pickup_delivery = parts[0].strip()
            delivery_charges = int(parts[1])

        pickup_delivery_date = request.POST.get('pickup_delivery_date','')
        print("pickup_delivery_date", pickup_delivery_date)


        pickup_delivery_time = request.POST.get('pickup_delivery_time','')
        pickup_delivery_time = pickup_delivery_time.strip()
        print('pickup_delivery_time :', pickup_delivery_time)

        delivery_addr = request.POST.get('delivery_address','')
        delivery_addr = delivery_addr.strip()
        print('delivery_addr :', delivery_addr)

        revised_price = cake_price
        print('revised_price : ', revised_price)  

        ordering_dt = datetime.now()

        product_desc = (
            f"Size {cake_size_weight_price}\n"           
            f"To be delivered on {pickup_delivery_date}"
            f" at {pickup_delivery_time}\n"
            f"Delivery to {delivery_addr}\n"
            f"Contact Person: {contact_person}\n"
            f"Phone Number: {contact_number}   "
            f"Email: {contact_email}\n"
            )     
        print('product_desc :', product_desc)

        cart_product_form = CartAddProductForm(initial={
            'product_desc': product_desc,            # Pass product des description
            'quantity': qty,
            'revised_price' : revised_price
            })
        context = {
            'product': product,
            'product_desc': product_desc,
            'ordering_dt': ordering_dt,
            'ordering_confirm': True,
            'contact_person': contact_person,
            'contact_number': contact_number,
            'contact_email': contact_email,
            'quantity': qty,
            'cake_size': cake_size,
            'cake_weight': cake_weight,
            'cake_desc': cake_desc,
            'cake_price': cake_price,
            'pickup_delivery': pickup_delivery,
            'pickup_delivery_time': pickup_delivery_time,
            'pickup_delivery_date': pickup_delivery_date,
            'delivery_addr': delivery_addr,
            'delivery_charges': delivery_charges,
            'revised_price': revised_price,
            'cart_product_form': cart_product_form
            }  
 
    return render(request,
                  'shop1/ordering.html',
                  context)
                   

templates/shop1/category.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}

{% block title %}
  {% if products %}Browse Cakes By Catalog: {{category_name}}{% endif %}
{% endblock %}

{% block content %}
  <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12" style="background-color: #e5c9a3;">
          {% if products %}
          <h1 class="display-4"> Browse Cakes: <b>{{category_name}}</b> Catalog </h1>
          {% endif %}
          <p class="lead">
            Sharing the cake with loved ones, it represents the joy, happiness, celebrations and thanksgiving.
          </p>
        </div>
      </div>
    </div>
  </section>
  
  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <i class="fas fa-home"></i> 
            <a href="/shop1/">Order Cakes</a>
          </li>
          {% if products %}
          <li class="breadcrumb-item">Browse Cakes By Catalog: {{category_name}} </li>
          {% endif %}
        </ol>
      </nav>
    </div>
  </section>
  
  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">
        <!-- Listing 1 -->
        {% comment %}
        {% if listings %}
        {% for listing in listings %}
        {% endcomment %}
        {% if products %}
        {% for product in products %} 
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            <img class="card-img-top" src={{product.image.url}} alt="" />
            <div class="card-img-overlay">
              <h2>
                <!--<span class="badge badge-secondary text-white">${{product.price | intcomma }}</span>-->
                <span class="badge badge-secondary text-white" style="background-color: #e9bf85;">${{product.price | intcomma }}</span>
              </h2>
            </div>
            <div class="card-body">
              <div class="listing-heading text-center">
                <h4 class="text-primary">{{product.name}}</h4>
                <p style="text-align: left;">
                  <!--<i class="fas fa-map-marker text-secondary"></i>{{product.description}}-->
                  <i class="fas fa-folder-open " style="color: #e9bf85"></i>  
                  <span style="font-size: 15px;">{{category_name}}</span> 
                  <br />
                  <i class="fas fa-tags" style="color: #e9bf85"></i>
                  <span style="font-size: 15px;">{{product.description}}</span>  
                </p>
              </div>
              {% comment %}  
              <hr />
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-th-large"></i> Sqft: {{listing.sqft | intcomma}}
                </div>
                <div class="col-6">
                  <i class="fas fa-dumbbell"></i> ClubHouse: {{listing.clubhouse}}
                </div>
              </div>
              <div class="row py-2 text-secondary">
                <div class="col-6"><i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}</div>
                <div class="col-6"><i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}</div>
              </div>
              {% endcomment %}
              {% comment %}
              <hr />
              <div class="row py-2 text-secondary">
                <div class="col-12"><i class="fas fa-user"></i> {{listing.realtor}}</div>
              </div>
              <div class="row text-secondary pb-2">
                <div class="col-6"><i class="fas fa-clock"></i> {{listing.list_date | timesince}}</div>
              </div>
              {% endcomment %}
              <hr />
              <a href="{% url 'shop1:product_detail' product.id product.category_id %}" class="btn btn-primary btn-block">Cake Ordering</a>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-md-12">
        <p>No Available Product</p>
      </div>
        {% endif %}
      
      </div>
  
      <div class="row">
        <div class="col-md-12">
          <!-- pagination part of the code-->
          {% if list.has_other_pages %}
          <ul class="pagination">
            {% if list.has_previous %}
            <li class="page-item">
              <a href="?page={{list.previous_page_number}}" class="page-link">&laquo;</a>
            </li>  
            {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#">&laquo;</a>
            </li>
            {% endif %}
            <!-- use for loop to gen page numbers -->
            {% for i in list.paginator.page_range %}
            <!-- check current page, then change the button color -->
            {% if list.number == i %}
            <li class="page-item active">
              <a class="page-link">{{i}}</a>
            </li>
            {% else %}
           <li class="page-item">
              <a class="page-link" href="?page={{i}}">{{i}}</a>
            </li> 
            {% endif %}
            {% endfor %}
            
            <!-- next button -->
            {% if list.has_next %}
            <li class="page-item">
            <a href="?page={{list.next_page_number}}" class="page-link" >&raquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#">&raquo;</a>
            </li>
            {% endif %}
          </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/shop1/detail.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }} | {{ product.name }} {% else %}{% endif %}
{% endblock %}

{% block content %}

<style>
  
    .background {
        background-image: url("{% static 'img/common-img/backg02.jpg' %}"); /* Adjust the path */
        background-size: cover; /* Cover the entire container */
        background-position: center; /* Center the image */
        background-repeat: no-repeat; /* Prevent repeating */
        height: 200vh; /* Full viewport height */
        position: relative; /* Position for absolute children if needed */
    }

  .card-body-small {
    padding: 0.4rem; /* Reduced padding */
    font-size: 0.6rem; /* Smaller font size */}

</style>


<div class='background'>


<!-- Listing -->
<section id="listing" class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-3">

        <!-- Product Name and Main Image -->
        <div class="card text-center mb-1">
          <div class="card-body-small">
          <h6 class="text-center">{{ product.name }}</h6>
          <img src="{{ product.image.url }}" alt="" class="img-main img-fluid mb-3" />
          </div>
        </div>
        
        <!---------Prodcut Description------------>

        <div class="card text-center mb-1">
          <div class="card-body-small">
            <p class="card-text">
              {{product.description}}
            </p>
          </div>
        </div>

        <!-- Allergen Information -->
        <div class="card text-center mb-1">
          <div class="card-body-small">
            <h6>Allergen Note:</h6>
            <p class="card-text">
              {% if product_detail_items %}
                {% for item in product_detail_items %}
                  {{ item.allergen }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
              {% endif %}
            </p>
          </div>
        </div>
      </div>

      
      <div class="col-md-6">

        <div class="card text-center mb-1">
          <h6 class="card-title">Order Details</h6>

          <div class="card-body-small">
            

            <!-- Send Out Ordering -->

          
          
          <form action="{% url 'shop1:ordering' product.id product.slug %}" method="POST" class="card-body-small ">

                <div class="card mb-1">
                  <div style="text-align: left;">
                    Quantity<small class="text-danger">*</small><br>
                  <select name="qty" id="qty" class="card-body-small w-30" required>
                      <option value="1">Qty: 1</option><!-- Default option -->
                      <option value="2">Qty: 2</option>
                      <option value="3">Qty: 3</option>
                      <option value="4">Qty: 4</option>
                      <option value="5">Qty: 5</option>
                  </select>
                  <br>
                  </div>

               
                
                  <div style="text-align: left;"><br>
                    Size<small class="text-danger">*</small><br>
                      <select name="cake_size_weight_price" class="card-body-small w-70">
                        {% if product_detail_items %}
                          {% for item in product_detail_items %}
                            <option value="{{ item.First_size }}/{{ item.First_weight }}/{{ item.First_desc }}/{{ item.First_price }}">
                              Size: {{ item.First_size }} / Weight: {{ item.First_weight }} / {{ item.First_desc }} / ${{ item.First_price }}
                            </option>
                            <option value="{{ item.Second_size }}/{{ item.Second_weight }}/{{ item.Second_desc }}/{{ item.Second_price }}">
                              Size: {{ item.Second_size }} / Weight: {{ item.Second_weight }} / {{ item.Second_desc }} / ${{ item.Second_price }}
                            </option>
                            <option value="{{ item.Third_size }}/{{ item.Third_weight }}/{{ item.Third_desc }}/{{ item.Third_price }}">
                              Size: {{ item.Third_size }} / Weight: {{ item.Third_weight }} / {{ item.Third_desc }} / ${{ item.Third_price }}
                            </option>
                            <option value="{{ item.Fourth_size }}/{{ item.Fourth_weight }}/{{ item.Fourth_desc }}/{{ item.Fourth_price }}">
                              Size: {{ item.Fourth_size }} / Weight: {{ item.Fourth_weight }} / {{ item.Fourth_desc }} / ${{ item.Fourth_price }}
                            </option>
                          {% endfor %}
                        {% endif %}
                      </select>
                      <br><br>
                    </div>
                      <div style="text-align: left;">
                      Contact Person<small class="text-danger">*</small><br>
                      <input type="text" class="card-body-small " name="contact_person" required />
                      </div>
                      <br>

                      <div style="text-align: left;">
                      Contact Number<small class="text-danger">*</small><br>
                          <input type="text" class="card-body-small" name="contact_number" pattern="[0-9]{8}" maxlength="8" required />
                          <div class="invalid-feedback">Contact Number must be 8 digits.</div>
                      </div>
                      <br>

                      <div style="text-align: left;">
                      Contact Email<small class="text-danger">*</small><br>
                      <input type="email" class="card-body-small" name="contact_email" required />
                      </div>
                      <br>
                      

                <!-- Select pickup delivery location -->
                <div style="text-align: left;">Pickup In / Delivery To <small class="text-danger">*</small><br>
                <select name="pickup_delivery" class="card-body-small">

                <option value="Pickup In Store - Fortress Hill [Hong Kong Island] /0">Pickup In Store: Fortress Hill [Hong Kong Island]</option>
                <option value="Pickup In Store - Mei Foo [Kowloon] /0">Pickup In Store: Mei Foo [Kowloon]</option>
                <option value="Pickup In Store - Tseung Kwan O [New Territories] /0">Pickup In Store: Tseung Kwan O [New Territories]</option>
                <option value="Delivery To - Hong Kong Island /0">Delivery To - Hong Kong Island</option>
                <option value="Delivery To - Kowloon /0">Delivery To - Kowloon</option>
                <option value="Delivery To - New Territories /0">Delivery To - New Territories</option>
                <option value="Delivery To - Islands /0">Delivery To - Islands</option>
                </select>
                </div>
                <br>

                      <div style="text-align: left;">Date [<font color="red">Earliest</font> pickup / delivery date <small class="text-danger">*</small><br>
                            <b>{{ fastest }}</b>
                        <select name="pickup_delivery_date" class="card-body-small">
                          {% if delivery_date.items %}
                            {% for key, value in delivery_date.items %}
                              <option value="{{ value }}">{{ value }}</option>
                            {% endfor %}
                          {% endif %}
                        </select>
                      </div>
                      <br>
          
                      <div style="text-align: left;">Pick up / delivery time <small class="text-danger">*</small><br>
                        <select name="pickup_delivery_time" class="card-body-small">
                          <option value="10am - 2pm">10am - 2pm</option>
                          <option value="2pm - 6pm">2pm - 6pm</option>
                          <option value="6pm - 9pm">6pm - 9pm</option>
                        </select>
                      </div>
                      <br>
          
                      <div style="text-align: left;">
                        Delivery Address<br>
                        <input type="text" class="card-body-small w-70" name="delivery_address" />
                      </div>
                      <br>
          
        </div>
              {% csrf_token %}
              <button class="btn btn-secondary btn-block mt-1" type="submit">Confirm</button>
              </form>
          
        </div>
      </div>
    </div>


        <!--- Store Locations ------>
        <div class="col-md-3">
        
          <div class="card text-center mb-1">
            <div class="card-body-small">
              <h6 class="card-title">Store Locations</h6>
              <p class="card-text">
                <p style="text-align: left;">
                  <span style="background-color: #ced4da; padding: 5px; border-radius: 4px;">[Hong Kong Island] Fortress Hill</span><br />
                  M/F, Greenwich Centre, No.260 King's Road, Fortress Hill, Hong Kong
                  <small class="form-text text-muted" style="text-align: right; background-color: #f9f5f5; padding: 5px; border-radius: 4px;">MTR station: Fortress Hill (Exit B)</small>
                </p>
                <hr>
                <p style="text-align: left;">
                  <span style="background-color: #ced4da; padding: 5px; border-radius: 4px;">[Kowloon] Mei Foo</span><br />
                  G/F, Phase 7, Mount Sterling Mall, Mei Foo, Kowloon  
                  <small class="form-text text-muted" style="text-align: right; background-color: #f9f5f5; padding: 5px; border-radius: 4px;">MTR station: Mei Foo (Exit E)</small>
                </p>
                <hr>
                <p style="text-align: left;">
                  <span style="background-color: #ced4da; padding: 5px; border-radius: 4px;">[New Territories] Tseung Kwan O</span><br />
                  Shop no. 1A, level 6, East Point City, 8 Chung Wa Road, Tseung Kwan O
                  <small class="form-text text-muted" style="text-align: right; background-color: #f9f5f5; padding: 5px; border-radius: 4px;">MTR station: Hang Hau (Exit A1)</small>
                </p>
              </p>
              <div class="card-footer text-muted">
                Store Business Hours: <br />
                (Daily) 10am - 9pm
              </div>
            </div>
          </div>
        </div>
  


    </div>
  </div>
</section>

<script>

  document.querySelector("form").addEventListener("submit", function(event) {
      const contactPersonInput = document.querySelector("input[name='contact_person']");
      if (!contactPersonInput.value.trim()) {
          alert("Contact Person is required.");
          event.preventDefault(); // Prevent form submission
      }
  });

  document.querySelector("form").addEventListener("submit", function(event) {
    const contactNumberInput = document.querySelector("input[name='contact_number']");
    if (!contactNumberInput.value.trim()) {
        alert("Contact Phone number is required.");
        event.preventDefault(); // Prevent form submission
    }
    
  document.querySelector("form").addEventListener("submit", function(event) {
      const contactemailInput = document.querySelector("input[name='contact_email']");
      if (!contactemailInput.value.trim()) {
          alert("Contact Email address is required.");
          event.preventDefault(); // Prevent form submission
      }
    });



  </script>

</div>

{% endblock %}